# Site settings
title: Urutau
email: info@urutau.co.nz
url: https://urutau.co.nz
description: "Resilient, healthy, and inclusive communities. Our purpose is to bridge research and practice to enable our communities to adapt to the changing climate."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Urutau

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/urutau-nz

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - '*.ini'
